services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    restart: always
    command: --check-caps false --ISCAgent false
    ports:
      - 1972
      - 52773
      - 53773
    volumes:
      - ./:/home/irisowner/dev
    environment:
        - LLM=${LLM}
        - LLM_MODEL=${LLM_MODEL}
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - GROQ_API_KEY=${GROQ_API_KEY}
        - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
